server:
  port: 8090

spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/,http://127.0.0.1:8083/eureka/
# 构建路由地址
zuul:
  routes:
    # 这里可以自定义
    users:
      # 匹配的路由规则
      path: /users/**
      # 路由的目标服务名
      #serviceId: eureka-provider
      url: users
# 关闭使用eureka负载路由
ribbon:
  eureka:
    enabled: false
# 如果不使用eureka的话，需要自己定义路由的那个服务的其他负载服务
users:
  ribbon:
    # 这里写你要路由的demo服务的所有负载服务请求地址，本项目只启动一个，因此只写一个
    listOfServers: http://localhost:8002/,http://localhost:8003/