server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zmn?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: eureka-provider

eureka:
  hostname: 127.0.0.1
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    instance-id: ${spring.application.name}:${server.port}
    statusPageUrl: http://${eureka.hostname}:${server.port}/actuator/info
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/,http://127.0.0.1:8083/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 8

info:
  app:
    name: ${spring.application.name}:${server.port}
    author: provider